# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://incubate.co.th
title: Incubate Co., Ltd.
email: suchit@incubate.co.th
author: Suchit Pongnumkul, PhD.
description: > # "Write an awesome description for your new site here. 
  Incubate Intelligence to Innovation.
copyright: 'Copyright &copy; 2019 Incubate Co., Ltd. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: medium
    url: https://medium.com/incubate-co-th
  - title: github
    url: https://github.com/ioisup/ioisup.github.io
  - title: linkedin
    url: https://www.linkedin.com/in/suchitpongnumkul/
